# Generated by Django 5.2.4 on 2025-09-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
