# Generated by Django 5.2.4 on 2025-09-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0004_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('remarcado', 'Remarcado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
